metadata:
  name: Partner Sales
  description: DLBA properties sold to community partners
  timeframe: To date
views:
  ago:
    destination: ago
    id: 1bb071e094ee4b059ec1abd36f5f91c8
    export: geojson
    select: select
              c.address,
              c.parcel_id,
              ac.property_class,
              a.actual_closing_date::timestamp as actual_closing_date,
              'Community Partner & Projects'::text as program,
              c.neighborhood,
              c.council_district,
              st_setsrid(st_makepoint(c.acct_longitude::numeric, c.acct_latitude::numeric), 4326) as geom
            from dlba.case c
              inner join dlba.dlba_activity a on a.case = c.id
              inner join dlba.account ac on ac.related_property_case_id = c.id
            where a.dlba_activity_type in ('Bridging Neighborhoods Sale', 'Community Partner Sale', 'Economic Development') 
              and a.sale_status = 'Closed'
              and a.actual_closing_date::timestamp >= date '2016-01-01'
              and c.address not like '%Fake St%'
            order by a.actual_closing_date::timestamp desc