metadata:
  name: Side Lots Sold
  description: All side lots sold by the DLBA
  timeframe: To date
views: 
  ago:
    destination: ago
    id: 1528d20710624632bf155fd67b57b963
    export: geojson
    select: select
              a.actual_closing_date::timestamp as actual_closing_date,
              a.sale_status,
              c.address,
              c.parcel_id,
              c.program,
              c.neighborhood,
              c.council_district,
              pb.buyer_status,
              pb.final_sale_price as final_sale_price,
              pb.purchaser_type,
              st_setsrid(st_makepoint(c.acct_longitude::numeric, c.acct_latitude::numeric), 4326) as geom
            from dlba.dlba_activity a
              inner join dlba.case c on a.case = c.id
              inner join dlba.prospective_buyer pb on pb.dlba_activity = a.id
            where a.recordtypeid = '012j0000000xtGvAAI'
              and a.actual_closing_date is not null
              and pb.buyer_status = 'Selected'
              and c.address not like '%Fake St%'
