
metadata:
  name: Certificates of Occupancy
  description: All CoOs issued by BSEED
  timeframe: 
views:
  socrata:
    destination: socrata
    id: kkg3-uzx5
    method: replace
    select: select
              per."B1_ALT_ID" AS record_id,
              initcap(
                regexp_replace(
                  concat_ws(
                    ' ',
                    addr."B1_HSE_NBR_START",
                    addr."B1_STR_DIR",
                    addr."B1_STR_NAME",
                    addr."B1_STR_SUFFIX"
                  ),
                  '[\s,]{1,}',
                  ' ',
                  'g'
                )
              ) as address,
              own."B1_OWNER_FULL_NAME" as owner_name,
              proc."SD_APP_DES" as status,
              des."B1_WORK_DESC" as description,
              (
                select
                  "B1_CHECKLIST_COMMENT"
                from
                  bchckbox
                where
                  bchckbox."B1_PER_ID1" = per."B1_PER_ID1"
                  and bchckbox."B1_PER_ID3" = per."B1_PER_ID3"
                  and bchckbox."B1_CHECKBOX_DESC_ALIAS" = 'Estimated Cost of Construction By Contractor/Homeowner'
                  limit 1
              ) as estimated_cost,
              accela.clean_pnum(par."B1_PARCEL_NBR") as parcel_number,
              makeSocrataDate(proc."G6_STAT_DD") as issue_date
            from
              b1permit per
              left outer join b3addres addr on addr."B1_PER_ID1" = per."B1_PER_ID1"
              and addr."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3parcel par on par."B1_PER_ID1" = per."B1_PER_ID1"
              and par."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join gprocess proc on proc."B1_PER_ID1" = per."B1_PER_ID1"
              and proc."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join bworkdes des on des."B1_PER_ID1" = per."B1_PER_ID1"
              and des."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3owners own on own."B1_PER_ID1" = per."B1_PER_ID1"
              and own."B1_PER_ID3" = per."B1_PER_ID3"
            where
              per."B1_PER_GROUP" = 'Permits'
              and per."B1_PER_TYPE" = 'Building'
              and per."B1_PER_SUB_TYPE" = 'Application'
              and proc."SD_APP_DES" = 'CofO Issued'
              and own."B1_PRIMARY_OWNER" = 'Y'
              and proc."REC_DATE"::timestamp > '2018-12-08'
            order by proc."G6_STAT_DD"::timestamp desc
            