metadata:
  name: Demolition Permits
  description: Demolition permits issued by BSEED
  timeframe: 
views:
  socrata:
    destination: socrata
    id: gxt7-3br7
    method: replace
    select: select
      distinct on (per."B1_ALT_ID")
              per."B1_ALT_ID" as record_id,
              initcap(
                regexp_replace(
                  concat_ws(
                    ' ',
                    addr."B1_HSE_NBR_START",
                    addr."B1_STR_DIR",
                    addr."B1_STR_NAME",
                    addr."B1_STR_SUFFIX"
                  ),
                  '[\s,]{1,}',
                  ' ',
                  'g'
                )
              ) as address,
              par."B1_COUNCIL_DISTRICT" as council,
              accela.clean_pnum(par."B1_PARCEL_NBR") as parcel_number,
              par."B1_PARCEL_AREA" as area_parcel,
              makeSocrataDate(proc."G6_STAT_DD") as permit_issue_date,
              '' as permit_type,
              '' as type_of_use,
              des."B1_WORK_DESC" as permit_description,
              (
                select
                  "B1_CHECKLIST_COMMENT"
                from
                  bchckbox
                where
                  bchckbox."B1_PER_ID1" = per."B1_PER_ID1"
                  and bchckbox."B1_PER_ID3" = per."B1_PER_ID3"
                  and bchckbox."B1_CHECKBOX_DESC_ALIAS" = 'Estimated Cost of Construction By Contractor/Homeowner'
              ) as estimate,
              det."BALANCE" as amount_due,
              det."TOTAL_PAY" as amount_paid,
              own."B1_OWNER_FULL_NAME" as owner_name,
              contr."B1_BUS_NAME" as contractor_name,
              regexp_replace(
                concat_ws(
                  ' ',
                  contr."B1_ADDRESS1",
                  contr."B1_ADDRESS2",
                  contr."B1_ADDRESS3",
                  contr."B1_CITY",
                  contr."B1_STATE",
                  contr."B1_ZIP"
                ),
                '[\s,]{1,}',
                ' ',
                'g'
              ) as contractor_address,
              contr."B1_PHONE1" as contractor_phone,
              '' as contractor_email,
              proc."SD_APP_DES" as status,
              proc."SD_PRO_DES" as task
            from
              b1permit per
              left outer join b3addres addr on addr."B1_PER_ID1" = per."B1_PER_ID1"
              and addr."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3parcel par on par."B1_PER_ID1" = per."B1_PER_ID1"
              and par."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3owners own on own."B1_PER_ID1" = per."B1_PER_ID1"
              and own."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join bworkdes des on des."B1_PER_ID1" = per."B1_PER_ID1"
              and des."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join bpermitdetail det on det."B1_PER_ID1" = per."B1_PER_ID1"
              and det."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3contra contr on contr."B1_PER_ID1" = per."B1_PER_ID1"
              and contr."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join gprocess proc on proc."B1_PER_ID1" = per."B1_PER_ID1"
              and proc."B1_PER_ID3" = per."B1_PER_ID3"
            where
              per."REC_DATE"::timestamp >= '2018-12-08'
              and per."B1_PER_GROUP" = 'Permits'
              and per."B1_PER_TYPE" = 'Demolition'
              and per."B1_APPL_STATUS" = 'Issued'
              and own."B1_PRIMARY_OWNER" = 'Y'
              and addr."B1_PRIMARY_ADDR_FLG" = 'Y'
              and par."B1_PRIMARY_PAR_FLG" = 'Y'
              and proc."SD_PRO_DES" = 'Permit Issuance'
              and proc."SD_APP_DES" = 'Issued'