metadata:
  name: Registered Contractors - Wrecking
  description: Wrecking contractors who are registered with BSEED
  timeframe: 
views:
  socrata:
    destination: socrata
    id: jfu2-2cpi
    method: replace
    select: select
              contr."B1_LICENSE_NBR" as license_number,
              per."B1_PER_SUB_TYPE" as sub_type,
              proc."SD_PRO_DES" as task,
              per."B1_APPL_STATUS" as category,
              contr."B1_LICENSE_TYPE" as license_type,
              trim(concat_ws(' ', contr."B1_CAE_FNAME", contr."B1_CAE_MNAME", contr."B1_CAE_LNAME")) as name_fml,
              contr."B1_ADDRESS1" as address,
              contr."B1_CITY" as city,
              contr."B1_STATE" as state,
              contr."B1_ZIP" as zip,
              contr."B1_BUS_NAME" as business_name,
              contr."B1_BUS_NAME2" as business_name_two,
              makeSocrataDate(contr."B1_LIC_EXPIR_DD") as license_expiration,
              makeSocrataDate(contr."B1_LAST_UPDATE_DD") as license_issued,
              makeSocrataDate(contr."B1_LAST_RENEWAL_DD") as license_renewed,
              proc."SD_APP_DES" as status
            from b1permit per
              left outer join b3addres addr on addr."B1_PER_ID1" = per."B1_PER_ID1"
                and addr."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3parcel par on par."B1_PER_ID1" = per."B1_PER_ID1"
                and par."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3owners own on own."B1_PER_ID1" = per."B1_PER_ID1"
                and own."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join bworkdes des on des."B1_PER_ID1" = per."B1_PER_ID1"
                and des."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join bpermitdetail det on det."B1_PER_ID1" = per."B1_PER_ID1"
                and det."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join bchckbox chck on chck."B1_PER_ID1" = per."B1_PER_ID1"
                and chck."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3contra contr on contr."B1_PER_ID1" = per."B1_PER_ID1"
                and contr."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join gprocess proc on proc."B1_PER_ID1" = per."B1_PER_ID1"
                and proc."B1_PER_ID3" = per."B1_PER_ID3"
            where per."B1_PER_SUB_TYPE" = 'WreckingContractor'
              AND proc."SD_PRO_DES" = 'License Issuance'
            order by contr."B1_LAST_UPDATE_DD"::timestamp desc nulls last