
metadata:
  name: Residential Inspections
  description: Residential inspections
  timeframe: 
views:
  socrata:
    destination: socrata
    id: nna2-7cpn
    method: replace
    select: select
              per."B1_ALT_ID" as record_id,
              own."B1_OWNER_FULL_NAME" as owner_name,
              initcap(
                regexp_replace(
                  concat_ws(
                    ' ',
                    addr."B1_HSE_NBR_START",
                    addr."B1_STR_DIR",
                    addr."B1_STR_NAME",
                    addr."B1_STR_SUFFIX"
                  ),
                  '[\s,]{1,}',
                  ' ',
                  'g'
                )
              ) as address,
              addr."B1_SITUS_ZIP" as zip,
              act."G6_ACT_TYP" as inspection_type,
              makeSocrataDate("G6_ACT_DD") as scheduled_date,
              makeSocrataDate(act."G6_COMPL_DD") as date_inspection,
              act."G6_STATUS" as result,
              accela.clean_pnum(par."B1_PARCEL_NBR") as parcel_number
            from
              b1permit per
              left outer join b3addres addr on addr."B1_PER_ID1" = per."B1_PER_ID1"
              and addr."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3parcel par on par."B1_PER_ID1" = per."B1_PER_ID1"
              and par."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join g6action act on act."B1_PER_ID1" = per."B1_PER_ID1"
              and act."B1_PER_ID3" = per."B1_PER_ID3"
              left outer join b3owners own on own."B1_PER_ID1" = per."B1_PER_ID1"
              and own."B1_PER_ID3" = per."B1_PER_ID3"
            where
              "G6_ACT_DD" != ''
              and "G6_ACT_DD"::timestamp > '2019-01-01'
              and act."G6_ACT_GRP" = 'Inspection'
              and own."B1_PRIMARY_OWNER" = 'Y'
              and per."B1_PER_GROUP" = 'CodeEnforcement'
              and per."B1_PER_TYPE" in ('Inspections')
              and per."B1_PER_SUB_TYPE" = 'Residential'